// DOM Elements
const jokeText = document.getElementById('jokeText');
const jokeType = document.getElementById('jokeType');
const getJokeBtn = document.getElementById('getJokeBtn');
const shareBtn = document.getElementById('shareBtn');
const copyBtn = document.getElementById('copyBtn');
const spinner = document.getElementById('loadingSpinner');
const errorMessage = document.getElementById('errorMessage');
const successMessage = document.getElementById('successMessage');
const categorySelect = document.getElementById('categorySelect');
const jokeCount = document.getElementById('jokeCount');

// State
let currentJoke = '';
let jokesLoaded = 0;

// API Configuration
const JOKE_API_URLS = {
    random: 'https://api.api-ninjas.com/v1/jokes?limit=1',
    general: 'https://official-joke-api.appspot.com/random_joke',
    programming: 'https://official-joke-api.appspot.com/jokes/programming/random',
    'knock-knock': 'https://official-joke-api.appspot.com/jokes/knock-knock/random'
};

// We'll use JokeAPI.dev for better reliability
const MAIN_API = 'https://v2.jokeapi.dev/joke/';

// Event Listeners
getJokeBtn.addEventListener('click', fetchJoke);
shareBtn.addEventListener('click', shareJoke);
copyBtn.addEventListener('click', copyToClipboard);
categorySelect.addEventListener('change', resetDisplay);

// Fetch joke from API
async function fetchJoke() {
    const category = categorySelect.value;
    
    // Show loading state
    getJokeBtn.disabled = true;
    spinner.style.display = 'block';
    errorMessage.style.display = 'none';
    shareBtn.style.display = 'none';
    copyBtn.style.display = 'none';

    try {
        let apiUrl = '';

        // Build API URL based on category
        if (category === 'random') {
            // Get random category excluding explicit jokes
            apiUrl = `${MAIN_API}Any?blacklistFlags=explicit&type=single,twopart`;
        } else if (category === 'general') {
            apiUrl = `${MAIN_API}Any?blacklistFlags=explicit&type=single,twopart`;
        } else if (category === 'programming') {
            apiUrl = `${MAIN_API}Programming?type=single,twopart`;
        } else if (category === 'knock-knock') {
            apiUrl = `${MAIN_API}Knock-Knock?type=twopart`;
        }

        const response = await fetch(apiUrl);

        if (!response.ok) {
            throw new Error(`API Error: ${response.status}`);
        }

        const data = await response.json();

        if (data.error) {
            throw new Error('Failed to fetch joke');
        }

        // Format and display the joke
        displayJoke(data);
        jokesLoaded++;
        jokeCount.textContent = jokesLoaded;
        
        // Show action buttons
        shareBtn.style.display = 'inline-block';
        copyBtn.style.display = 'inline-block';

    } catch (error) {
        showError(error.message || 'Failed to fetch joke. Please try again.');
        console.error('Error fetching joke:', error);
    } finally {
        // Hide loading state
        getJokeBtn.disabled = false;
        spinner.style.display = 'none';
    }
}

// Display the joke
function displayJoke(jokeData) {
    // Handle different API response formats
    if (jokeData.type === 'single') {
        currentJoke = jokeData.joke;
        jokeText.textContent = jokeData.joke;
        jokeType.textContent = '📝 Single Liner';
    } else if (jokeData.type === 'twopart') {
        currentJoke = `${jokeData.setup}\n\n${jokeData.delivery}`;
        jokeText.textContent = currentJoke;
        jokeType.textContent = '🎭 Two Part Joke';
    } else if (jokeData.joke) {
        // Fallback for alternative API format
        currentJoke = jokeData.joke;
        jokeText.textContent = jokeData.joke;
        jokeType.textContent = '📝 Joke';
    }

    // Add animation to joke display
    jokeText.style.animation = 'none';
    setTimeout(() => {
        jokeText.style.animation = 'slideIn 0.5s ease-out';
    }, 10);
}

// Share joke functionality
function shareJoke() {
    if (!currentJoke) return;

    const text = `😂 Check out this joke:\n\n${currentJoke}\n\nGenerated by Joke Generator!`;

    // Check if Web Share API is available
    if (navigator.share) {
        navigator.share({
            title: 'Joke Generator',
            text: text
        }).catch(err => console.log('Error sharing:', err));
    } else {
        // Fallback: copy to clipboard and show message
        navigator.clipboard.writeText(text).then(() => {
            showSuccess('Joke copied to clipboard! Ready to share.');
        }).catch(() => {
            showError('Could not share. Please try copying instead.');
        });
    }
}

// Copy to clipboard
function copyToClipboard() {
    if (!currentJoke) return;

    navigator.clipboard.writeText(currentJoke).then(() => {
        showSuccess('Joke copied to clipboard!');
    }).catch(() => {
        showError('Failed to copy to clipboard.');
    });
}

// Show error message
function showError(message) {
    errorMessage.textContent = `❌ ${message}`;
    errorMessage.style.display = 'block';
}

// Show success message
function showSuccess(message) {
    successMessage.textContent = `✅ ${message}`;
    successMessage.style.display = 'block';
    setTimeout(() => {
        successMessage.style.display = 'none';
    }, 3000);
}

// Reset display when category changes
function resetDisplay() {
    jokeText.textContent = 'Click the button to get a random joke!';
    jokeType.textContent = '';
    shareBtn.style.display = 'none';
    copyBtn.style.display = 'none';
    currentJoke = '';
}

// Load a joke on page load
window.addEventListener('load', () => {
    // Optional: load a joke automatically when page loads
    // fetchJoke();
    console.log('Joke Generator Ready! Click "Get Random Joke" to start.');
});